# Generated by Django 4.1 on 2022-08-26 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default=product.models.get_category_image, max_length=255, null=True, upload_to=product.models.get_category_image_filepath)),
                ('icon', models.ImageField(blank=True, default=product.models.get_category_icon_image, max_length=255, null=True, upload_to=product.models.get_category_icon_image_filepath)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_banner', models.BooleanField(default=False)),
                ('is_mega', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_today_deal', models.BooleanField(default=False)),
                ('is_top_selling', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('gst', models.DecimalField(decimal_places=2, default='', max_digits=10)),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(default='pc', max_length=255)),
                ('num_of_sale', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('meta_title', models.TextField(default='save organic')),
                ('meta_description', models.TextField(default='save organic')),
                ('meta_img', models.ImageField(blank=True, upload_to='upload/products/meta')),
                ('short_desc', models.TextField(max_length=350)),
                ('long_desc', models.TextField(max_length=350)),
                ('auto_created', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
        ),
    ]
